// Emits the brand layer as CSS custom properties, from the same TypeScript the
// email templates import.
//
// It reads `src/` directly rather than the packed output, so it has no ordering
// relationship with `vp pack` — the two build steps are independent and cache
// separately.
//
// It emits layer one only. The mapping from these primitives onto the component
// library's contract is a design judgement and stays hand-written in
// packages/ui/src/styles/globals.css. See ADR-0024.

// Relative specifiers, not the `~` alias: node runs this file directly with
// native type stripping and resolves no tsconfig paths, so an alias here fails
// at run time rather than at build time.
/* oxlint-disable hadronomy/prefer-tilde-imports */

import { GenMapping, addMapping, toEncodedMap } from "@jridgewell/gen-mapping";
import { NodeRuntime, NodeServices } from "@effect/platform-node";
import { Effect, FileSystem, Path, Schema } from "effect";
import { transform } from "lightningcss";

import { color } from "../src/color.ts";
import { cornerGeometry, productImage, radius } from "../src/geometry.ts";
import { duration, easing } from "../src/motion.ts";
import { fontStack, textSize } from "../src/type.ts";

export class InvalidCss extends Schema.TaggedError<InvalidCss>()("InvalidCss", {
  reason: Schema.String,
}) {}

const kebab = (name: string) => name.replaceAll(/[A-Z]/g, (letter) => `-${letter.toLowerCase()}`);

/**
 * One custom property, and the token that produced it.
 *
 * `owner` is the source module; `key` is the identifier inside it. Together
 * they let the source map send a reader from a property in devtools to the line
 * that decides its value.
 */
interface Declaration {
  readonly property: string;
  readonly value: string;
  readonly owner: string;
  readonly key: string;
}

const declarations: ReadonlyArray<Declaration> = [
  ...Object.entries(color).map(([name, value]) => ({
    property: `--mze-${kebab(name)}`,
    value: value.oklch,
    owner: "color.ts",
    key: name,
  })),
  ...Object.entries(fontStack.web).map(([role, stack]) => ({
    property: `--mze-font-${role}`,
    value: stack,
    owner: "type.ts",
    key: role,
  })),
  ...Object.entries(textSize).flatMap(([step, { size, leading }]) => [
    { property: `--mze-text-${step}`, value: size, owner: "type.ts", key: step },
    { property: `--mze-leading-${step}`, value: leading, owner: "type.ts", key: step },
  ]),
  { property: "--mze-radius", value: radius, owner: "geometry.ts", key: "radius" },
  {
    property: "--mze-corner-shape",
    value: cornerGeometry,
    owner: "geometry.ts",
    key: "cornerGeometry",
  },
  {
    property: "--mze-product-aspect",
    value: productImage.aspect,
    owner: "geometry.ts",
    key: "aspect",
  },
  {
    property: "--mze-product-padding",
    value: productImage.padding,
    owner: "geometry.ts",
    key: "padding",
  },
  ...Object.entries(duration).map(([step, value]) => ({
    property: `--mze-duration-${step}`,
    value,
    owner: "motion.ts",
    key: step,
  })),
  ...Object.entries(easing).map(([name, value]) => ({
    property: `--mze-ease-${name}`,
    value,
    owner: "motion.ts",
    key: name,
  })),
];

/**
 * Zero-based line that decides `key`, for the map's source position.
 *
 * Tokens are written two ways — as an object property (`leaf: { … }`) and as a
 * standalone export (`export const radius = …`). Matching only the first sends
 * every scalar token to line 1, which looks like it works until you click one.
 */
function lineOf(source: string, key: string): number {
  const property = new RegExp(`^\\s*"?${key}"?\\s*:`);
  const declaration = new RegExp(`^\\s*export const ${key}\\b`);
  const index = source
    .split("\n")
    .findIndex((line) => property.test(line) || declaration.test(line));
  return index < 0 ? 0 : index;
}

const header = "/* Generated by @mze-store/design-tokens. Edit src/, not this file. */";

/**
 * Renders the stylesheet and, in development, a source map that points each
 * property at the line which decides it.
 *
 * The map is authored rather than derived: there is no original document to
 * transform, so a diffing tool has nothing to map from and would emit an empty
 * `mappings` string.
 */
const render = Effect.fn("DesignTokens.render")(function* (withSourceMap: boolean) {
  const fs = yield* FileSystem.FileSystem;
  const path = yield* Path.Path;
  const srcDir = path.join(import.meta.dirname, "..", "src");

  const sources = new Map<string, string>();
  if (withSourceMap) {
    for (const owner of new Set(declarations.map((entry) => entry.owner))) {
      sources.set(owner, yield* fs.readFileString(path.join(srcDir, owner)));
    }
  }

  const map = new GenMapping({ file: "theme.css" });
  const lines = [header, ":root {"];

  for (const { property, value, owner, key } of declarations) {
    const generatedLine = lines.length;
    lines.push(`  ${property}: ${value};`);
    const source = sources.get(owner);
    if (source === undefined) continue;
    addMapping(map, {
      generated: { line: generatedLine + 1, column: 2 },
      source: `../src/${owner}`,
      original: { line: lineOf(source, key) + 1, column: 0 },
      content: source,
    });
  }
  lines.push("}", "");

  const css = lines.join("\n");
  return withSourceMap
    ? {
        css: `${css}/*# sourceMappingURL=theme.css.map */\n`,
        map: JSON.stringify(toEncodedMap(map)),
      }
    : { css, map: undefined };
});

/**
 * Parses the result before it is written.
 *
 * Without this, a malformed value reaches the browser as a silently dropped
 * declaration — the failure mode where the storefront loses a colour and
 * nothing anywhere reports why.
 */
const validate = Effect.fn("DesignTokens.validateCss")(function* (css: string) {
  yield* Effect.try({
    try: () => transform({ filename: "theme.css", code: Buffer.from(css), minify: false }),
    catch: (cause) => new InvalidCss({ reason: String(cause) }),
  });
});

const emit = Effect.fn("DesignTokens.emitThemeCss")(function* () {
  const fs = yield* FileSystem.FileSystem;
  const path = yield* Path.Path;

  // A source map embeds the token modules verbatim. Shipping it would publish
  // them to anyone who opens devtools, so production gets the stylesheet alone.
  //
  // The switch is an argument rather than `process.env.NODE_ENV` on purpose:
  // the task runner caches on the command string, so an environment variable
  // read in here is invisible to it and a development result gets replayed into
  // a production build. As a flag it is part of the cache key.
  const withSourceMap = process.argv.includes("--source-map");

  const { css, map } = yield* render(withSourceMap);
  yield* validate(css);

  const outDir = path.join(import.meta.dirname, "..", "dist");
  yield* fs.makeDirectory(outDir, { recursive: true });
  yield* fs.writeFileString(path.join(outDir, "theme.css"), css);

  const mapPath = path.join(outDir, "theme.css.map");
  if (map === undefined) {
    // A stale map from an earlier development build must not survive into a
    // production artifact.
    yield* fs.remove(mapPath).pipe(Effect.ignore);
  } else {
    yield* fs.writeFileString(mapPath, map);
  }
});

emit().pipe(Effect.provide(NodeServices.layer), NodeRuntime.runMain);
